db:
  image: postgres:9.4.1
  ports:
    - "5432:5432"

frontend:
  image: tutum/hipache
  environment:
    - SERVER_TCPTIMEOUT=1
    - SERVER_DEADBACKENDON500=true
  ports:
    - "80:80"
    - "6379:6379"

backenda:
  build: ./simple_rails_app
  environment:
    - DOMAIN=docker.dev
  links:
    - db
    - frontend
  ports:
    - '3000'

backendb:
  build: ./simple_rails_app
  environment:
    - DOMAIN=docker.dev
  links:
    - db
    - frontend
  ports:
    - '3000'



