db:
  image: postgres:9.4.1
  ports:
    - "5432:5432"

backend:
  build: ./simple_rails_app
  links:
    - db
  ports:
    - '3000'
  volumes:
    - ./simple_rails_app:/myapp

frontend:
  image: tutum/hipache
  ports:
    - "80:80"
    - "6379:6379"


